// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStartupFile() {
  return window['go']['main']['App']['GetStartupFile']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function OpenFileDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2, arg3);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ResolvePath(arg1) {
  return window['go']['main']['App']['ResolvePath'](arg1);
}

export function SaveFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2, arg3, arg4);
}

export function SaveFileDialog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2, arg3, arg4);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetDirty(arg1) {
  return window['go']['main']['App']['SetDirty'](arg1);
}

export function SetDocPath(arg1) {
  return window['go']['main']['App']['SetDocPath'](arg1);
}
