// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetStartupFiles():Promise<Array<string>>;

export function LoadSettings():Promise<main.Settings>;

export function OpenFileDialog(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function Quit():Promise<void>;

export function ReadFile(arg1:string):Promise<main.Document>;

export function ResolvePath(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SetDirty(arg1:boolean):Promise<void>;

export function SetDocPath(arg1:string):Promise<void>;
