// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ExportDialog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportDialog'](arg1, arg2, arg3, arg4);
}

export function ExportPDF(arg1, arg2) {
  return window['go']['main']['App']['ExportPDF'](arg1, arg2);
}

export function GetStartupFiles() {
  return window['go']['main']['App']['GetStartupFiles']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportTargets(arg1, arg2) {
  return window['go']['main']['App']['ImportTargets'](arg1, arg2);
}

export function IsDefaultMarkdownApp() {
  return window['go']['main']['App']['IsDefaultMarkdownApp']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function OpenFileDialog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2, arg3, arg4);
}

export function OpenWithDefaultApp(arg1) {
  return window['go']['main']['App']['OpenWithDefaultApp'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileBase64(arg1) {
  return window['go']['main']['App']['ReadFileBase64'](arg1);
}

export function ResolvePath(arg1) {
  return window['go']['main']['App']['ResolvePath'](arg1);
}

export function SaveFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2, arg3, arg4);
}

export function SaveFileDialog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2, arg3, arg4);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetDirty(arg1) {
  return window['go']['main']['App']['SetDirty'](arg1);
}

export function SetDocPath(arg1) {
  return window['go']['main']['App']['SetDocPath'](arg1);
}

export function ShowDefaultAppDialog() {
  return window['go']['main']['App']['ShowDefaultAppDialog']();
}

export function WasUpdated() {
  return window['go']['main']['App']['WasUpdated']();
}

export function WriteBase64File(arg1, arg2) {
  return window['go']['main']['App']['WriteBase64File'](arg1, arg2);
}
