// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyUpdate():Promise<void>;

export function CheckForUpdate():Promise<main.UpdateCheck>;

export function ExportDialog(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ExportPDF(arg1:string,arg2:string):Promise<void>;

export function GetStartupFiles():Promise<Array<string>>;

export function GetVersion():Promise<string>;

export function ImportTargets(arg1:string,arg2:Array<string>):Promise<main.ImportTarget>;

export function IsDefaultMarkdownApp():Promise<boolean>;

export function LoadSettings():Promise<main.Settings>;

export function OpenFileDialog(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<string>>;

export function OpenWithDefaultApp(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function ReadFile(arg1:string):Promise<main.Document>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function ResolvePath(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SetDirty(arg1:boolean):Promise<void>;

export function SetDocPath(arg1:string):Promise<void>;

export function ShowDefaultAppDialog():Promise<void>;

export function WasUpdated():Promise<boolean>;

export function WriteBase64File(arg1:string,arg2:string):Promise<void>;
